Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2022-10, with the labels that each got.

#50 mdd-ported-samples
  samples/grids/grid/batch-editing.json
  samples/grids/grid/multi-row-layout-style.json
  samples/grids/grid/paste.json
Labels: status: in-review

#52 Create with-rating.json
  samples/grids/grid/with-rating.json
Labels: status: in-review

#54 mdd-PORT-setup-grid-samples
  samples/grids/grid/action-strip.json
  samples/grids/grid/advanced-filtering.json
  samples/grids/grid/crud.json
  samples/grids/grid/custom-filtering.json
  samples/grids/grid/custom-kb-navigation.json
  samples/grids/grid/custom-remote-paging-sample.json
  samples/grids/grid/custom-summaries-selection.json
  samples/grids/grid/external-advanced-filtering.json
  samples/grids/grid/filtering-template-sample.json
  samples/grids/grid/groupby-custom-sample.json
  samples/grids/grid/remote-data-operations.json
Labels: status: in-review

#61 mdd-PORT-samples (unfinished)
  samples/grids/grid/sample-4.json
  samples/grids/grid/sample-5.json
  samples/grids/grid/validator-service-extended.json
Labels: status: in-review

#63 mdd-NOTES
  samples/grids/grid/action-strip.txt
  samples/grids/grid/crud.txt
  samples/grids/grid/custom-filtering.txt
  samples/grids/grid/custom-kb-navigation.txt
  samples/grids/grid/custom-remote-paging-sample.txt
  samples/grids/grid/custom-summaries-selection.txt
  samples/grids/grid/external-advanced-filtering.txt
  samples/grids/grid/filtering-template-sample.txt
  samples/grids/grid/grid-nested-data-binding.txt
  samples/grids/grid/groupby-custom-sample.txt
  samples/grids/grid/paste.txt
  samples/grids/grid/remote-filtering-sample.txt
  samples/grids/grid/sample-4.txt
  samples/grids/grid/sample-5.txt
  samples/grids/grid/validator-service-cross-field-extended.txt
  samples/grids/grid/validator-service-cross-field.txt
Labels: status: in-review

#66 mdd-chart-aggregation
  samples/charts/category-chart/data-aggregations.json
Labels: status: in-review

#68 grid pager sample
  samples/grids/grid/grid-pager-sample.json
  samples/grids/grid/grid-pager-sample.txt
Labels: status: in-development, status: in-review

#67 Add xplat configuration for grid-formatted-filtering-strategy sample
  samples/grids/grid/formatted-filtering-strategy.json
Labels: status: in-review

#65 Add column data types sample config
  samples/grids/grid/column-data-types.json
Labels: status: in-review

#76 grid multi cell selection style
  samples/grids/grid/multi-cell-selection.json
Labels: status: in-review

#83 Add rowStyles sample
  samples/grids/grid/rowStyles-sample.json
Labels: status: in-review

#71 Add configuration for grid-row-pinning sample
  samples/grids/grid/grid-row-pinning.json
Labels: status: in-development

#85 Add grid filtering samples config
  samples/grids/grid/grid-custom-filtering.json
  samples/grids/grid/grid-filtering-style.json
  samples/grids/grid/grid-filtering-template.json
  samples/grids/grid/grid-filtering.json
Labels: status: in-development

#102 Add configuration for grid rowclasses sample
  samples/grids/grid/row-classes.json
Labels: status: in-development

#99 Add advanced-filtering sample.
  samples/grids/grid/advanced-filtering-options.json
Labels: status: in-development
