Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2023-09, with the labels that each got.

#282 chart samples with value format specifiers
  samples/charts/category-chart/format-specifiers.json
  samples/charts/data-chart/format-specifiers.json
  samples/charts/financial-chart/format-specifiers.json
Labels: status: in-review

#306 Add WebGridMasterDetailTemplate for React
  code-gen-library/WebGridMasterDetailTemplate/React.tsx
Labels: status: verified

#309 Add pin header template for React
  code-gen-library/WebGridPinHeaderTemplate/React.ts
Labels: status: verified

#312 Add couple of templates for the overview topic samples
  code-gen-library/WebGridCompositeAddressCellTemplate/React.tsx
  code-gen-library/WebGridCompositeAddressEditCellTemplate/React.tsx
  code-gen-library/WebGridCompositeContactCellTemplate/React.tsx
  code-gen-library/WebGridCompositeContactEditCellTemplate/React.tsx
  code-gen-library/WebGridNestedDataCellTemplate/React.tsx
Labels: status: verified

#322 [React] Add WebGridFilterAltIconTemplate
  code-gen-library/WebGridFilterAltIconTemplate/React.ts
Labels: platform: react, status: verified
