Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2023-06, with the labels that each got.

#212 mdd-remove-export-false
  samples/charts/toolbar/layout-actions-for-data-chart.json
  samples/charts/toolbar/layout-in-vertical-orientation.json
  samples/charts/toolbar/theming.json
Labels: status: in-review

#208 mdd-wpf-custom-actions-for-data-chart
  samples/charts/toolbar/custom-actions-for-data-chart.json
  samples/charts/toolbar/theming.json
Labels: status: in-review

#217 mdd-toolbar-updates-with-cc-sample
  samples/charts/toolbar/actions-built-in-category-chart.json
  samples/charts/toolbar/actions-built-in-data-chart.json
  samples/charts/toolbar/custom-actions-for-data-chart.json
  samples/charts/toolbar/layout-actions-for-data-chart.json
  samples/charts/toolbar/layout-in-vertical-orientation.json
  samples/charts/toolbar/theming.json
Labels: status: in-review

#225 Enable groupby summary styling.
  samples/grids/grid/groupby-summary-styling.json
Labels: platform: blazor, platform: web-comp

#228 added style template ref to ESF Styling sample
  samples/grids/grid/excel-style-filtering-style.json
Labels: status: in-development

#252 Update layout-actions-for-data-chart.json
  samples/charts/toolbar/layout-actions-for-data-chart.json
Labels: status: in-review

#254 Update data-aggregations.json
  samples/charts/category-chart/data-aggregations.json
Labels: status: in-review
