Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2023-12, with the labels that each got.

#429 Fix conditional row selectors sample for WC and Blazor.
  code-gen-library/WebGridRowSelectionConditional/Blazor.js
  code-gen-library/WebGridRowSelectionConditional/Web.ts
Labels: status: verified

#433 [React] Update WebGridWithComboRendered template
  code-gen-library/WebGridWithComboRendered/React.tsx
Labels: status: in-review, platform: react

#265 Add tree grid sorting topic samples.
  samples/grids/tree-grid/column-sorting-indicators.json
  samples/grids/tree-grid/column-sorting-options.json
  samples/grids/tree-grid/column-sorting-style.json
Labels: status: verified

#257 Update treegrid editing-lifecycle sample
  samples/grids/tree-grid/editing-lifecycle.json
Labels: status: verified

#258 Add custom kb nav sample for treegrid.
  code-gen-library/WebGridCustomKBNav/Blazor.js
  samples/grids/tree-grid/keyboard-custom-navigation.json
Labels: status: verified

#253 Update sample to use Paginator instead of deprecated paging prop. Als…
  samples/grids/tree-grid/overview.json
Labels: status: verified

#437 Fix React duplicate templates and wrong extensions
  code-gen-library/CategoryChartCustomSelectionPointerDown/React.tsx
  code-gen-library/ToolbarToggleTooltip/React.tsx
  code-gen-library/WebGridAvatarCellTemplate/React.tsx
  code-gen-library/WebGridBooleanCellTemplate/React.tsx
  code-gen-library/WebGridChangePercentTemplate/React.tsx
  code-gen-library/WebGridFilterAltIconTemplate/React.tsx
  code-gen-library/WebGridImageCellTemplate/React.ts
  code-gen-library/WebGridImageCellTemplate/React.tsx
  code-gen-library/WebGridPinHeaderTemplate/React.tsx
Labels: platform: react

#448 Update index.ts
  editor-templates/WebComponents/main-template/src/index.ts
Labels: status: in-review

#242 Add basic treegrid filtering samples.
  samples/grids/tree-grid/filtering-options.json
  samples/grids/tree-grid/filtering-style.json
Labels: status: in-review

#244 Add missing tGrid row selection samples
  code-gen-library/WebTreeGridRowSelectionConditional/Blazor.js
  code-gen-library/WebTreeGridRowSelectionConditional/Web.ts
  samples/grids/tree-grid/conditional-row-selectors.json
  samples/grids/tree-grid/row-selection-template-excel.json
Labels: status: in-review
