Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2023-10, with the labels that each got.

#311 Add WebGridBooleanCellTemplate for React
  code-gen-library/WebGridBooleanCellTemplate/React.ts
Labels: status: verified

#324 Add column resizing event handler
  code-gen-library/WebGridColumnResized/React.tsx
Labels: status: verified

#331 Add React template for Row Paging Basic and fix import.
  code-gen-library/WebGridProgressCellTemplate/React.tsx
  samples/grids/grid/row-paging-basic.json
Labels: status: verified

#335 mdd--react-webGridCurrencyCellTempalte
  code-gen-library/WebGridCurrencyCellTemplate/React.tsx
Labels: status: in-review

#227 Cell Editing Template Sample and Styling
  code-gen-library/WebGridCellEditCellTemplate/React.tsx
  samples/grids/grid/cell-editing-sample.json
  samples/grids/grid/cell-editing-styling.json
Labels: status: verified

#334 Add WebGridRowSelectorExcelTemplate for react.
  code-gen-library/WebGridRowSelectorExcelTemplate/React.tsx
Labels: status: verified

#284 Add typography class to each sample container in each template
  editor-templates/Angular/main-template/src/app.component.html
  editor-templates/Blazor/main-template/App.razor
  editor-templates/React/main-template/src/index.tsx
  editor-templates/WebComponents/main-template/index.html
Labels: status: blocked, status: in-review

#339 Add Rendered handler for cascading combo. Update templates to manage …
  code-gen-library/WebGridCityDropDownTemplate/React.tsx
  code-gen-library/WebGridCountryDropDownTemplate/React.tsx
  code-gen-library/WebGridRegionDropDownTemplate/React.tsx
  code-gen-library/WebGridWithComboRendered/React.tsx
Labels: status: verified

#346 WebGridRowEditDone - Add event arg type for react generation.
  code-gen-library/WebGridRowEditDone/Web.ts
Labels: status: verified

#344 Fix event arg type.
  code-gen-library/WebGridRowEditExit/Web.ts
Labels: status: verified

#345 Fix event args type.
  code-gen-library/WebGridRowEditEnter/Web.ts
Labels: status: verified

#356 [React] Add WebGridCellEdit event args type
  code-gen-library/WebGridCellEdit/Web.ts
Labels: platform: react, status: verified

#361 webGridEditingEventsCellEdit - Add event args type.
  code-gen-library/WebGridEditingEventsCellEdit/Web.ts
Labels: status: verified

#347 Add event args type and other minor fixes.
  code-gen-library/WebGridPinFirstGroupToggle/Web.ts
Labels: status: verified

#216 Enable column pinning styling sample.
  samples/grids/grid/column-pinning-styles.json
Labels: status: verified

#213 Enable groupby styling sample.
  samples/grids/grid/groupby-styling.json
Labels: status: verified

#221 Enable resizing styling sample.
  samples/grids/grid/column-resize-styling.json
Labels: status: verified

#348 Fix args and get column another way.
  code-gen-library/WebGridHideFirstGroupToggle/Web.ts
Labels: status: verified

#353 [React] Add WebGridCellEditEnter event args type
  code-gen-library/WebGridCellEditEnter/Web.ts
Labels: platform: react, status: verified

#352 [React] Fix WebGridCellEditExit event type arg
  code-gen-library/WebGridCellEditExit/Web.ts
Labels: platform: react, status: verified

#359 [React] Add WebGridColumnInitEvent event args type
  code-gen-library/WebGridColumnInitEvent/Web.ts
Labels: platform: react, status: verified

#351 [React] WebGridRowEdit fix event type arg
  code-gen-library/WebGridRowEdit/Web.ts
Labels: platform: react, status: verified

#224 Enable row pinning style sample.
  code-gen-library/WebGridPinRowOnRendered/Web.ts
  code-gen-library/WebGridRowPinStyleOnInitEvent/Blazor.js
  code-gen-library/WebGridRowPinStyleOnInitEvent/Web.ts
  samples/grids/grid/row-pinning-style.json
Labels: status: verified

#364 Delete unused JSON template for clipboard-operations and related event handlers
  code-gen-library/WebGridClearSelection/Blazor.js
  code-gen-library/WebGridClearSelection/Web.ts
  code-gen-library/WebGridClipboardOperationsColumnInit/Blazor.js
  code-gen-library/WebGridClipboardOperationsColumnInit/Web.ts
  samples/grids/grid/clipboard-operations.json
  samples/grids/tree-grid/clipboard-operations.json
Labels: status: in-review, platform: xplat

#222 Enable column selection styles sample.
  samples/grids/grid/column-selection-styles.json
Labels: status: verified

#204 Add toolbar to MRL sample
  samples/grids/grid/multi-row-layout-options.json
Labels: status: verified

#219 Add MCH styling sample
  samples/grids/grid/multi-column-headers-styling.json
Labels: status: verified

#237 Add advanced filtering styling sample.
  code-gen-library/WebTreeGridAdvancedFilteringStyle/Blazor.js
  code-gen-library/WebTreeGridAdvancedFilteringStyle/Web.ts
  samples/grids/tree-grid/advanced-filtering-style.json
Labels: status: verified

#248 Enable ESF style sample.
  samples/grids/grid/excel-style-filtering-style.json
Labels: status: verified

#238 Add tree grid col pinning samples
  samples/grids/tree-grid/column-pinning-styles.json
  samples/grids/tree-grid/column-pinning.json
Labels: status: verified

#235 Add cell selection styling sample
  samples/grids/tree-grid/cell-selection-style.json
Labels: status: verified

#234 Add excel export sample for Tree grid
  samples/grids/tree-grid/excel-exporting.json
  samples/grids/tree-grid/multi-column-headers-export.json
Labels: status: verified

#215 Enable cell selection style sample.
  samples/grids/grid/cell-selection-style.json
Labels: status: verified

#211 Add export excel group by sample. Change export excel MCH sample
  samples/grids/grid/excel-exporting.json
  samples/grids/grid/multi-column-headers-export.json
Labels: status: verified

#207 Add row editing style sample
  samples/grids/grid/row-editing-style.json
Labels: status: verified

#218 Add column moving xplat sample
  samples/grids/grid/column-moving-styles.json
Labels: status: verified

#367 Remove duplicate columns in layout-display-density.json
  samples/grids/grid/layout-display-density.json
Labels: platform: xplat

#376 Add id attribute to grid in filtering-style sample
  samples/grids/grid/filtering-style.json
Labels: platform: xplat, status: verified

#374 [React] Add support for Date objects in WebGridGroupByRowTemplate
  code-gen-library/WebGridGroupByRowTemplate/React.tsx
Labels: platform: react, status: verified

#256 Add tree grid row editing samples
  samples/grids/tree-grid/row-editing-options.json
  samples/grids/tree-grid/row-editing-style.json
Labels: status: do-not-merge

#243 Add column selection styling sample
  samples/grids/tree-grid/column-selection-style.json
Labels: status: do-not-merge

#239 Add TreeGrid col resizing style sample
  samples/grids/tree-grid/column-resize-styling.json
Labels: status: do-not-merge

#382 Delete React.ts
  code-gen-library/WebGridCurrencyCellTemplate/React.ts
Labels: status: in-review

#388 Add unique names for Property editor children so that it renders correctly for react.
  samples/grids/grid/data-summary-template.json
Labels: status: verified

#262 Port column-hiding-toolbar-style sample
  samples/grids/grid/column-hiding-toolbar-style.json
Labels: status: verified

#362 WebGridCustomKBNav - Fix event arg type and other types.
  code-gen-library/WebGridCustomKBNav/Web.ts
Labels: status: verified

#389 Enable conditional cell styling via class for Blazor/WC/React.
  code-gen-library/WebGridBeatsPerMinuteCellClassesHandler/Blazor.js
  code-gen-library/WebGridBeatsPerMinuteCellClassesHandler/Web.ts
  code-gen-library/WebGridBeatsPerMinuteTemplate/Blazor.js
  code-gen-library/WebGridBeatsPerMinuteTemplate/React.tsx
  code-gen-library/WebGridBeatsPerMinuteTemplate/WebComponents.ts
  code-gen-library/WebGridTopSpeedCellClassesHandler/Blazor.js
  code-gen-library/WebGridTopSpeedCellClassesHandler/Web.ts
  code-gen-library/WebGridTopSpeedTemplate/Blazor.js
  code-gen-library/WebGridTopSpeedTemplate/React.tsx
  code-gen-library/WebGridTopSpeedTemplate/WebComponents.ts
  samples/grids/grid/conditional-cell-style-1.json
Labels: status: verified

#260 Port MCH template sample. Add tree grid MHC samples.
  samples/grids/grid/multi-column-headers-template.json
  samples/grids/tree-grid/multi-column-headers-overview.json
  samples/grids/tree-grid/multi-column-headers-styling.json
  samples/grids/tree-grid/multi-column-headers-template.json
Labels: status: verified

#393 Fix SortingOptions to generate correctly
  samples/grids/grid/column-sorting-options.json
Labels: bug: in-sample, status: in-review, severity: low, platform: xplat

#405 Add specific React handler for WebGridExportEventMultiColumnHeaders since event type name has different name resolved.
  code-gen-library/WebGridExportEventMultiColumnHeaders/React.tsx
  code-gen-library/WebGridExportEventMultiColumnHeaders/WebComponents.ts
Labels: status: verified

#398 Update templates for composite binding data and nested data samples
  code-gen-library/WebGridCompositeAddressEditCellTemplate/Blazor.js
  code-gen-library/WebGridCompositeAddressEditCellTemplate/React.tsx
  code-gen-library/WebGridCompositeAddressEditCellTemplate/WebComponents.ts
  code-gen-library/WebGridCompositeContactCellTemplate/Blazor.js
  code-gen-library/WebGridCompositeContactCellTemplate/React.tsx
  code-gen-library/WebGridCompositeContactCellTemplate/WebComponents.ts
  code-gen-library/WebGridCompositeContactEditCellTemplate/Blazor.js
  code-gen-library/WebGridCompositeContactEditCellTemplate/React.tsx
  code-gen-library/WebGridCompositeContactEditCellTemplate/WebComponents.ts
  code-gen-library/WebGridNestedDataCellTemplate/Blazor.js
  code-gen-library/WebGridNestedDataCellTemplate/React.tsx
  code-gen-library/WebGridNestedDataCellTemplate/WebComponents.ts
  samples/grids/grid/binding-composite-data.json
  samples/grids/grid/binding-nested-data-1.json
Labels: status: in-review, status: verified

#404 Add tree grid hide and pin first group templates. Some minor fixes.
  code-gen-library/WebGridPinFirstGroupToggle/Web.ts
  code-gen-library/WebTreeGridHideFirstGroupToggle/Blazor.cs
  code-gen-library/WebTreeGridHideFirstGroupToggle/Web.ts
  code-gen-library/WebTreeGridPinFirstGroupToggle/Blazor.cs
  code-gen-library/WebTreeGridPinFirstGroupToggle/Web.ts
  samples/grids/tree-grid/multi-column-headers-overview.json
Labels: severity: critical :boom:, status: verified
