Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2024-06, with the labels that each got.

#595 Add TreeGrid conditional styling samples
  code-gen-library/WebTreeGridAllergensCellClassesHandler/Blazor.js
  code-gen-library/WebTreeGridAllergensCellClassesHandler/Web.ts
  code-gen-library/WebTreeGridCellStylesHandler/Blazor.js
  code-gen-library/WebTreeGridCellStylesHandler/Web.ts
  code-gen-library/WebTreeGridUnitPriceCellClassesHandler/Blazor.js
  code-gen-library/WebTreeGridUnitPriceCellClassesHandler/Web.ts
  samples/grids/tree-grid/conditional-cell-style-1.json
  samples/grids/tree-grid/conditional-cell-style-2.json
  samples/grids/tree-grid/row-classes.json
Labels: platform: blazor, platform: react, platform: web-comp, status: verified

#584 Add TreeGrid toolbar samples
  code-gen-library/WebTreeGridAvatarCellTemplate/Blazor.js
  code-gen-library/WebTreeGridAvatarCellTemplate/React.tsx
  code-gen-library/WebTreeGridAvatarCellTemplate/WebComponents.ts
  code-gen-library/WebTreeGridToolbarExporting/Blazor.js
  code-gen-library/WebTreeGridToolbarExporting/Web.ts
  samples/grids/tree-grid/toolbar-sample-1.json
  samples/grids/tree-grid/toolbar-sample-3.json
  samples/grids/tree-grid/toolbar-style.json
Labels: platform: blazor, platform: react, platform: web-comp

#604 Add tree grid summary samples
  code-gen-library/WebTreeGridChangeSummaryCalculationMode/Blazor.js
  code-gen-library/WebTreeGridChangeSummaryCalculationMode/React.tsx
  code-gen-library/WebTreeGridChangeSummaryCalculationMode/Web.ts
  code-gen-library/WebTreeGridChangeSummaryPosition/Blazor.js
  code-gen-library/WebTreeGridChangeSummaryPosition/React.tsx
  code-gen-library/WebTreeGridChangeSummaryPosition/Web.ts
  code-gen-library/WebTreeGridHasSummariesChange/Blazor.cs
  code-gen-library/WebTreeGridHasSummariesChange/Web.ts
  code-gen-library/WebTreeGridSummariesHeaderTemplate/Blazor.js
  code-gen-library/WebTreeGridSummariesHeaderTemplate/React.tsx
  code-gen-library/WebTreeGridSummariesHeaderTemplate/WebComponents.ts
  code-gen-library/WebTreeGridSummaryFormatter/Blazor.js
  code-gen-library/WebTreeGridSummaryFormatter/Web.ts
  code-gen-library/WebTreeGridSummaryStyle/Blazor.js
  code-gen-library/WebTreeGridSummaryStyle/Web.ts
  code-gen-library/WebTreeGridSummaryTemplate/Blazor.js
  code-gen-library/WebTreeGridSummaryTemplate/React.tsx
  code-gen-library/WebTreeGridSummaryTemplate/WebComponents.ts
  config.json
  samples/grids/tree-grid/data-summary-children.json
  samples/grids/tree-grid/data-summary-formatter.json
  samples/grids/tree-grid/data-summary-options-styling.json
  samples/grids/tree-grid/data-summary-options.json
  samples/grids/tree-grid/data-summary-template.json
Labels: status: verified

#627 mdd-updates
  samples/charts/data-chart/data-legend-grouping-and-highlighting.json
  samples/charts/data-chart/data-legend-grouping.json
  samples/charts/data-chart/data-legend-styling.json
  samples/charts/data-chart/data-tooltip-grouping-and-highlighting.json
  samples/charts/data-chart/data-tooltip-grouping.json
  samples/charts/data-chart/data-tooltip-styling.json
  samples/gauges/radial-gauge/highlight-needle.json
Labels: status: in-review

#597 Add tgrid row reorder ample
  code-gen-library/WebTreeGridReorderRowHandler/Blazor.js
  code-gen-library/WebTreeGridReorderRowHandler/React.ts
  code-gen-library/WebTreeGridReorderRowHandler/Web.ts
  code-gen-library/WebTreeGridReorderRowStartHandler/Blazor.js
  code-gen-library/WebTreeGridReorderRowStartHandler/React.ts
  code-gen-library/WebTreeGridReorderRowStartHandler/Web.ts
  samples/grids/tree-grid/row-reorder.json
Labels: status: verified

#629 fix(tree-grid): enable samples for react
  config.json
Labels: platform: react

#638 fix(tree-grid): refactor cell editing samples
  code-gen-library/WebTreeGridCellEdit/Web.ts
  samples/grids/tree-grid/cell-editing-styling.json
  samples/grids/tree-grid/editing-columns.json
  samples/grids/tree-grid/editing-events.json
Labels: platform: blazor, platform: react, platform: web-comp, status: verified

#639 Mdd update highlight label
  samples/gauges/radial-gauge/highlight-needle.json
Labels: status: in-review

#640 mdd-angular-18
  editor-templates/Angular/main-template/package.json
Labels: status: in-review

#641 fix(tree-grid-cell-editing): set correct data and import select module
  code-gen-library/WebTreeGridCellEditCellTemplate/WebComponents.ts
  samples/grids/tree-grid/cell-editing-sample.json
Labels: platform: web-comp

#646 Removing unnecessary react template and replacing deprecated event args
  code-gen-library/WebTreeGridReorderRowStartHandler/React.ts
  code-gen-library/WebTreeGridReorderRowStartHandler/Web.ts
Labels: status: verified

#647 Update package.json
  editor-templates/Angular/main-template/package.json
Labels: status: in-review

#649 treemap highlighting - remove "export": false,
  samples/charts/tree-map/highlighting.json
Labels: status: in-review

#613 update hammer js
  editor-templates/Angular/main-template/package.json
Labels: status: in-review

#655 Mdd chart selection
  samples/charts/category-chart/selection-modes.json
  samples/charts/category-chart/selection-multiple-modes.json
  samples/charts/data-chart/radial-column-chart-selection.json
Labels: status: in-review

#657 mdd-update-angular-packages-6-24
  editor-templates/Angular/main-template/package.json
Labels: status: in-review
