Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2024-09, with the labels that each got.

#693 Fix issue with toolbar exporting evt args - react.
  code-gen-library/WebGridToolbarExporting/React.tsx
Labels: status: verified

#704 Adjust method name so there's no name collisions.
  code-gen-library/WebHierarchicalGridColumnGroupHeaderTemplate/Blazor.js
Labels: status: verified

#715 Fix incorrect primaryKey in hGrid multi-column headers overview JSON sample
  samples/grids/hierarchical-grid/multi-column-headers-overview.json
Labels: status: in-review, platform: xplat

#717 Update GroupBy styling to be more visible.
  code-gen-library/WebGridGroupByStyleWithCustomCSS/Blazor.js
  code-gen-library/WebGridGroupByStyleWithCustomCSS/Web.ts
Labels: status: verified

#720 Add config for NwindData to resolve to plain json for React and WC.
  code-gen-library/NwindData/XPLAT-CONFIG.json
Labels: status: verified :heavy_check_mark:
