Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2024-04, with the labels that each got.

#559 mdd-new-gauge-samples
  samples/gauges/bullet-graph/highlight-needle.json
  samples/gauges/linear-gauge/highlight-needle.json
  samples/gauges/radial-gauge/highlight-needle.json
  samples/gauges/radial-gauge/title-styling.json
Labels: status: in-review

#560 Mdd update gauges highlight needle updates
  samples/gauges/linear-gauge/highlight-needle.json
  samples/gauges/radial-gauge/highlight-needle.json
Labels: status: in-review

#561 Update BlazorClientApp.csproj
  editor-templates/Blazor/main-template/BlazorClientApp.csproj
Labels: status: in-review

#564 mdd-199
  editor-templates/Blazor/main-template/BlazorClientApp.csproj
Labels: status: in-review

#565 mdd-casing-test-issue-code-gen
  samples/charts/data-chart/scatter-bubble-chart-fill-scale.json
Labels: status: in-review, bug: in-code-viewer

#567 mdd-angular-17.3.0
  editor-templates/Angular/main-template/package.json
Labels: status: in-review

#536 Add hgrid editing samples
  code-gen-library/WebHierarchicalGridCellEdit/Blazor.js
  code-gen-library/WebHierarchicalGridCellEdit/React.tsx
  code-gen-library/WebHierarchicalGridCellEdit/Web.ts
  code-gen-library/WebHierarchicalGridCellEditDone/Blazor.js
  code-gen-library/WebHierarchicalGridCellEditDone/React.tsx
  code-gen-library/WebHierarchicalGridCellEditDone/Web.ts
  code-gen-library/WebHierarchicalGridCellEditEnter/Blazor.js
  code-gen-library/WebHierarchicalGridCellEditEnter/React.tsx
  code-gen-library/WebHierarchicalGridCellEditEnter/Web.ts
  code-gen-library/WebHierarchicalGridCellEditExit/Blazor.js
  code-gen-library/WebHierarchicalGridCellEditExit/React.tsx
  code-gen-library/WebHierarchicalGridCellEditExit/Web.ts
  code-gen-library/WebHierarchicalGridRendered/Blazor.js
  code-gen-library/WebHierarchicalGridRendered/React.tsx
  code-gen-library/WebHierarchicalGridRendered/Web.ts
  code-gen-library/WebHierarchicalGridRowEdit/Blazor.js
  code-gen-library/WebHierarchicalGridRowEdit/React.tsx
  code-gen-library/WebHierarchicalGridRowEdit/Web.ts
  code-gen-library/WebHierarchicalGridRowEditDone/Blazor.js
  code-gen-library/WebHierarchicalGridRowEditDone/React.tsx
  code-gen-library/WebHierarchicalGridRowEditDone/Web.ts
  code-gen-library/WebHierarchicalGridRowEditEnter/Blazor.js
  code-gen-library/WebHierarchicalGridRowEditEnter/React.tsx
  code-gen-library/WebHierarchicalGridRowEditEnter/Web.ts
  code-gen-library/WebHierarchicalGridRowEditExit/Blazor.js
  code-gen-library/WebHierarchicalGridRowEditExit/React.tsx
  code-gen-library/WebHierarchicalGridRowEditExit/Web.ts
  code-gen-library/WebRowIslandGridCellEdit/Blazor.js
  code-gen-library/WebRowIslandGridCellEdit/React.tsx
  code-gen-library/WebRowIslandGridCellEdit/Web.ts
  code-gen-library/WebRowIslandGridCellEditDone/Blazor.js
  code-gen-library/WebRowIslandGridCellEditDone/React.tsx
  code-gen-library/WebRowIslandGridCellEditDone/Web.ts
  code-gen-library/WebRowIslandGridCellEditEnter/Blazor.js
  code-gen-library/WebRowIslandGridCellEditEnter/React.tsx
  code-gen-library/WebRowIslandGridCellEditEnter/Web.ts
  code-gen-library/WebRowIslandGridCellEditExit/Blazor.js
  code-gen-library/WebRowIslandGridCellEditExit/React.tsx
  code-gen-library/WebRowIslandGridCellEditExit/Web.ts
  code-gen-library/WebRowIslandGridRowEdit/Blazor.js
  code-gen-library/WebRowIslandGridRowEdit/React.tsx
  code-gen-library/WebRowIslandGridRowEdit/Web.ts
  code-gen-library/WebRowIslandGridRowEditDone/Blazor.js
  code-gen-library/WebRowIslandGridRowEditDone/React.tsx
  code-gen-library/WebRowIslandGridRowEditDone/Web.ts
  code-gen-library/WebRowIslandGridRowEditEnter/Blazor.js
  code-gen-library/WebRowIslandGridRowEditEnter/React.tsx
  code-gen-library/WebRowIslandGridRowEditEnter/Web.ts
  code-gen-library/WebRowIslandGridRowEditExit/Blazor.js
  code-gen-library/WebRowIslandGridRowEditExit/React.tsx
  code-gen-library/WebRowIslandGridRowEditExit/Web.ts
  samples/grids/hierarchical-grid/editing-lifecycle.json
Labels: status: verified

#506 Add hgrid display density samples
  samples/grids/hierarchical-grid/layout-display-density.json
Labels: status: verified

#503 Add hgrid hiding samples
  code-gen-library/WebHierarchicalGridHidingStyle/Blazor.js
  code-gen-library/WebHierarchicalGridHidingStyle/Web.ts
  code-gen-library/WebHierarchicalGridHidingTemplate/Blazor.js
  code-gen-library/WebHierarchicalGridHidingTemplate/React.tsx
  code-gen-library/WebHierarchicalGridHidingTemplate/Web.ts
  samples/grids/hierarchical-grid/column-hiding-toolbar-style.json
  samples/grids/hierarchical-grid/column-hiding-toolbar.json
Labels: status: verified

#569 chore(hgrid): rename IgcExporterEvent to IgcExporterEventArgs
  code-gen-library/WebHierarchicalGridExportMultiColumnHeaders/Web.ts
Labels: status: verified

#550 Add hgrid summary samples
  code-gen-library/WebHierarchicalGridHasSummariesChange/Blazor.cs
  code-gen-library/WebHierarchicalGridHasSummariesChange/Web.ts
  code-gen-library/WebHierarchicalGridRenderedExpand/Blazor.js
  code-gen-library/WebHierarchicalGridRenderedExpand/React.tsx
  code-gen-library/WebHierarchicalGridRenderedExpand/Web.ts
  code-gen-library/WebHierarchicalGridSummaryFormatter/Blazor.js
  code-gen-library/WebHierarchicalGridSummaryFormatter/Web.ts
  code-gen-library/WebHierarchicalGridSummaryStyle/Blazor.js
  code-gen-library/WebHierarchicalGridSummaryStyle/Web.ts
  code-gen-library/WebHierarchicalGridSummaryTemplate/Blazor.razor
  code-gen-library/WebHierarchicalGridSummaryTemplate/React.tsx
  code-gen-library/WebHierarchicalGridSummaryTemplate/WebComponents.ts
  code-gen-library/WebHierarchicalGridSummaryTemplateStyle/Blazor.razor
  code-gen-library/WebHierarchicalGridSummaryTemplateStyle/React.tsx
  code-gen-library/WebHierarchicalGridSummaryTemplateStyle/WebComponents.ts
  code-gen-library/WebRowIslandGridSummaryTemplateStyle/Blazor.razor
  code-gen-library/WebRowIslandGridSummaryTemplateStyle/React.tsx
  code-gen-library/WebRowIslandGridSummaryTemplateStyle/WebComponents.ts
  samples/grids/hierarchical-grid/data-summary-formatter.json
  samples/grids/hierarchical-grid/data-summary-options-styling.json
  samples/grids/hierarchical-grid/data-summary-options.json
  samples/grids/hierarchical-grid/data-summary-template.json
Labels: status: verified

#543 Add hgrid Row Reorder sample
  code-gen-library/WebHierarchicalGridReorderRowHandler/Blazor.js
  code-gen-library/WebHierarchicalGridReorderRowHandler/Web.ts
  samples/grids/hierarchical-grid/row-reorder.json
Labels: status: verified

#531 Add hgrid row editing samples
  code-gen-library/WebHierarchicalGridRowEditingStyle/Blazor.js
  code-gen-library/WebHierarchicalGridRowEditingStyle/Web.ts
  samples/grids/hierarchical-grid/row-editing-options.json
  samples/grids/hierarchical-grid/row-editing-style.json
Labels: status: verified

#530 Add hGrid toolbar samples
  code-gen-library/WebHierarchicalGridToolbarExporting/Blazor.js
  code-gen-library/WebHierarchicalGridToolbarExporting/Web.ts
  code-gen-library/WebHierarchicalGridToolbarTemplate/Blazor.js
  code-gen-library/WebHierarchicalGridToolbarTemplate/React.tsx
  code-gen-library/WebHierarchicalGridToolbarTemplate/WebComponents.ts
  config.json
  samples/grids/hierarchical-grid/toolbar-sample-1.json
  samples/grids/hierarchical-grid/toolbar-sample-2.json
  samples/grids/hierarchical-grid/toolbar-sample-3.json
  samples/grids/hierarchical-grid/toolbar-style.json
Labels: status: verified

#526 Add hgrid selection samples
  code-gen-library/WebRowIslandCellSelectionChange/Blazor.js
  code-gen-library/WebRowIslandCellSelectionChange/React.tsx
  code-gen-library/WebRowIslandCellSelectionChange/Web.ts
  samples/grids/hierarchical-grid/cell-selection-mode.json
Labels: status: verified

#524 Add HierarchicalGrid row selection samples
  code-gen-library/WebHierarchicalGridRowSelectionConditional/Blazor.js
  code-gen-library/WebHierarchicalGridRowSelectionConditional/Web.ts
  samples/grids/hierarchical-grid/conditional-row-selectors.json
  samples/grids/hierarchical-grid/row-selection-mode.json
  samples/grids/hierarchical-grid/row-selection-template-numbers.json
Labels: status: verified

#513 Add hgrid cell selection samples
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Blazor.js
  code-gen-library/WebHierarchicalGridCellSelectionStyling/React.tsx
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Web.ts
  samples/grids/hierarchical-grid/cell-selection-overview.json
  samples/grids/hierarchical-grid/cell-selection-styling.json
Labels: status: verified

#507 Added CellEditing samples,data and templates
  code-gen-library/HGridCellEditCellTemplate/Blazor.js
  code-gen-library/HGridCellEditCellTemplate/React.tsx
  code-gen-library/HGridCellEditCellTemplate/WebComponents.ts
  code-gen-library/HGridDndData/XPLAT-CONFIG.json
  code-gen-library/HGridDndData/XPLAT.json
  code-gen-library/HGridEditingEvents/Blazor.js
  code-gen-library/HGridEditingEvents/React.tsx
  code-gen-library/HGridEditingEvents/Web.ts
  code-gen-library/WebGridCellEditingStyleTemplate/Web.ts
  samples/grids/hierarchical-grid/cell-editing-sample.json
  samples/grids/hierarchical-grid/cell-editing-styling.json
  samples/grids/hierarchical-grid/editing-columns.json
  samples/grids/hierarchical-grid/editing-events.json
Labels: status: verified

#511 Add hgrid column moving samples
  code-gen-library/HierarchicalCustomers/XPLAT-CONFIG.json
  code-gen-library/HierarchicalCustomers/XPLAT.json
  samples/grids/hierarchical-grid/column-moving-options.json
  samples/grids/hierarchical-grid/column-moving-styles.json
Labels: status: verified

#517 Add hgrid sorting samples
  code-gen-library/WebHierarchicalGridSortingStyling/Blazor.js
  code-gen-library/WebHierarchicalGridSortingStyling/Web.ts
  samples/grids/hierarchical-grid/column-sorting-indicators.json
  samples/grids/hierarchical-grid/column-sorting-options.json
  samples/grids/hierarchical-grid/column-sorting-style.json
Labels: status: verified

#518 Add hgrid row adding sample
  samples/grids/hierarchical-grid/row-adding.json
Labels: status: verified

#533 Added Samples and wc template
  code-gen-library/HGridPaginatorStyle/Blazor.js
  code-gen-library/HGridPaginatorStyle/Web.ts
  samples/grids/hierarchical-grid/hierarchical-grid-options.json
  samples/grids/hierarchical-grid/hierarchical-grid-paging-style.json
Labels: status: verified

#495 Added filtering samples for HGrid
  code-gen-library/SingersData/XPLAT.json
  code-gen-library/WebGridExcelStyleFilteringTemplate/Blazor.js
  code-gen-library/WebGridExcelStyleFilteringTemplate/Web.ts
  code-gen-library/WebGridToolbarDefaultTemplate/Blazor.js
  code-gen-library/WebGridToolbarDefaultTemplate/Web.ts
  code-gen-library/WebHGridAdvancedFilteringStyle/Blazor.js
  code-gen-library/WebHGridAdvancedFilteringStyle/Web.ts
  code-gen-library/WebHGridFilteringStyle/Blazor.js
  code-gen-library/WebHGridFilteringStyle/Web.ts
  samples/grids/hierarchical-grid/advanced-filtering-options.json
  samples/grids/hierarchical-grid/advanced-filtering-style.json
  samples/grids/hierarchical-grid/custom-filtering.json
  samples/grids/hierarchical-grid/excel-style-filtering-sample-1.json
  samples/grids/hierarchical-grid/excel-style-filtering-sample-2.json
  samples/grids/hierarchical-grid/excel-style-filtering-sample-3.json
  samples/grids/hierarchical-grid/excel-style-filtering-style.json
  samples/grids/hierarchical-grid/filtering-options.json
  samples/grids/hierarchical-grid/filtering-style.json
Labels: status: verified

#508 Add hgrid multi column headers samples
  code-gen-library/WebHierarchicalGridColumnGroupHeaderTemplate/Blazor.js
  code-gen-library/WebHierarchicalGridColumnGroupHeaderTemplate/React.tsx
  code-gen-library/WebHierarchicalGridColumnGroupHeaderTemplate/Web.ts
  code-gen-library/WebHierarchicalGridHideFirstGroupToggle/Blazor.cs
  code-gen-library/WebHierarchicalGridHideFirstGroupToggle/Web.ts
  code-gen-library/WebHierarchicalGridMultiColumnHeadersStyling/Blazor.js
  code-gen-library/WebHierarchicalGridMultiColumnHeadersStyling/Web.ts
  code-gen-library/WebHierarchicalGridPinFirstGroupToggle/Blazor.cs
  code-gen-library/WebHierarchicalGridPinFirstGroupToggle/Web.ts
  samples/grids/hierarchical-grid/multi-column-headers-overview.json
  samples/grids/hierarchical-grid/multi-column-headers-styling.json
  samples/grids/hierarchical-grid/multi-column-headers-template.json
Labels: status: verified

#581 fixed template naming
  code-gen-library/WebHGridAdvancedFilteringStyle/Blazor.js
  code-gen-library/WebHGridAdvancedFilteringStyle/Web.ts
Labels: status: verified

#501 Ttonev/h grid collapsible column groups
  samples/grids/hierarchical-grid/column-collapsible-groups.json
Labels: status: verified

#577 Add hgrid cell selection samples
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Blazor.js
  code-gen-library/WebHierarchicalGridCellSelectionStyling/React.tsx
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Web.ts
  samples/grids/hierarchical-grid/cell-selection-overview.json
  samples/grids/hierarchical-grid/cell-selection-styling.json
Labels: status: verified

#539 Add HierarchicalGrid row pinning samples
  code-gen-library/WebHierarchicalGridChangePinningConfig/Blazor.js
  code-gen-library/WebHierarchicalGridChangePinningConfig/React.tsx
  code-gen-library/WebHierarchicalGridChangePinningConfig/Web.ts
  code-gen-library/WebHierarchicalGridPinRowOnRendered/Blazor.js
  code-gen-library/WebHierarchicalGridPinRowOnRendered/React.tsx
  code-gen-library/WebHierarchicalGridPinRowOnRendered/Web.ts
  code-gen-library/WebHierarchicalGridRowPinCellTemplate/Blazor.js
  code-gen-library/WebHierarchicalGridRowPinCellTemplate/React.tsx
  code-gen-library/WebHierarchicalGridRowPinCellTemplate/Web.ts
  samples/grids/hierarchical-grid/row-pinning-extra-column.json
  samples/grids/hierarchical-grid/row-pinning-options.json
  samples/grids/hierarchical-grid/row-pinning-style.json
Labels: status: verified

#574 Fix react template to resolve missing container IgrHierarchicalGrid
  code-gen-library/WebHierarchicalGridRendered/React.tsx
Labels: status: verified

#523 Add hgrid row actions samples
  samples/grids/hierarchical-grid/action-strip.json
Labels: status: verified

#587 23.2.204
  editor-templates/Blazor/main-template/BlazorClientApp.csproj
Labels: status: in-review

#588 Fix Cell Selection sample name and styles.
  code-gen-library/WebGridCellSelectionStyleWithCustomCSS/Blazor.js
  code-gen-library/WebGridCellSelectionStyleWithCustomCSS/Web.ts
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Blazor.js
  code-gen-library/WebHierarchicalGridCellSelectionStyling/React.tsx
  code-gen-library/WebHierarchicalGridCellSelectionStyling/Web.ts
  samples/grids/hierarchical-grid/cell-selection-style.json
Labels: status: verified

#592 mdd-uniqueName-hGrid-blazor-columnGroupStates
  code-gen-library/WebHierarchicalGridColumnGroupHeaderTemplate/Blazor.js
Labels: status: in-review

#589 Update grid's id in CCG sample
  samples/grids/hierarchical-grid/column-collapsible-groups.json
Labels: status: verified

#605 Mdd highlighted percent based
  code-gen-library/CountryTopUrbanPopData/XPLAT.json
  samples/charts/tree-map/highlighting-percent-based.json
Labels: status: in-review
