Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2025-06, with the labels that each got.

#868 fix(react): grid cascading combo errors
  code-gen-library/WebGridWithComboRendered/React.tsx
Labels: platform: react

#876 mdd-Angular-19.1.0
  editor-templates/Angular/main-template/package.json
Labels: status: :green_book: in-review

#858 Updated Paste from excel template to take grid reference correctly for React
  code-gen-library/WebGridPasteFromExcel/Web.ts
Labels: status: verified :heavy_check_mark:
