Repository IgniteUI/igniteui-xplat-examples, pull requests merged in 2025-05, with the labels that each got.

#835 data-annotation-1
  editor-templates/WebComponents/main-template/package.json
  samples/charts/data-chart/data-annotation-band-layer.json
  samples/charts/data-chart/data-annotation-line-layer.json
  samples/charts/data-chart/data-annotation-multiple-with-overlay-text.json
  samples/charts/data-chart/data-annotation-multiple-with-stocks.json
  samples/charts/data-chart/data-annotation-rect-layer.json
  samples/charts/data-chart/data-annotation-slice-layer.json
  samples/charts/data-chart/data-annotation-strip-layer.json
Labels: status: :hammer_and_wrench: in-development

#842 mdd-update-grids-package
  editor-templates/WebComponents/main-template/package.json
Labels: status: :green_book: in-review

#833 36449
  code-gen-library/ShapeFileOnViewInit/Blazor.cs
  code-gen-library/ShapeFileStyling/Blazor.js
  samples/maps/geo-map/shape-styling.json
Labels: status: :green_book: in-review

#805 fix(samples): updated samples with correct key ID to recognize child …
  samples/grids/hierarchical-grid/multi-column-headers-styling.json
  samples/grids/hierarchical-grid/multi-column-headers-template.json
Labels: platform: xplat, status: verified :heavy_check_mark:

#857 19.1.0-beta.0
  editor-templates/Angular/main-template/package.json
Labels: status: :green_book: in-review

#859 Update package.json
  editor-templates/Angular/main-template/package.json
Labels: status: :closed_book: do-not-merge

#866 mdd-update-templates-data-grid-wc-react
  editor-templates/React/main-template/package.json
  editor-templates/WebComponents/main-template/package.json
Labels: status: :green_book: in-review
